Vagrant.configure("2") do |config|

  config.vm.box = "jpiel/ubuntu18.04"

  config.vm.network "private_network", ip: "192.168.56.110",

  name: "VirtualBox Host-Only Ethernet Adapter"

  config.vm.provider "virtualbox" do |vb|

     vb.memory = "1024"

     vb.cpus = "1"

  end

  config.vm.boot_timeout = 800

  config.vm.provision "file", source: "../ansible/host_vars/ssh/test_ssh.pub", destination: "~/.ssh/authorized_keys"

end
